### ISSUE TITLE
Thanks a lot!

### ISSUE THREAD

**Issue by sonictl** [msuliq/Samsung-SSD-970-EVO-Plus-2B2QEXM7#1]
firmware version 2B2QEXM7 is no longer available on the Samsung’s official website.

BUT How did you got it? *_*

the **4B2QEXM7** does not support my 970 evo plus.

Thanks a lot!

Thanks a lot!

**Comment by msuliq** [comment]
Hi, I had the same issue as you did and I also discovered that the firmware was no longer available on the official Samsung website. Since at that time I have read a lot of threads about this, I reached out to several people who had same issue and used 2B2QEXM7 asking if they still had copy of the firmware, and luckily one of them shared it with me.
I knew that someone else might need this too and that's why I created this repo. I am very glad that it helped you.
